### ISSUE TITLE
The tool produces broken result

### ISSUE THREAD

**Issue by greenozon** [Epoch1337/VMPStrings#1]
tested on VMP v3.6.0
produced result  testapp-decrypted.exe is broken, can't run
this behavior is observed even the tool decrypts 0 strings, despite the resultant exe gets bigger by 10-20%

**Comment by Epoch1337** [comment]
Can you post the target file?

Thanks.

**Comment by greenozon** [comment]
Yeah, looks like after saving -decrypted exe it has some issues with types loading, eg:

![image](https://user-images.githubusercontent.com/765343/231432798-ac7970c4-f825-406f-b3cc-ddbad5ed564d.png)

https://www.sendspace.com/file/51ff5l

MegDumpr.vmp-decrypted.exe  isproduced by the tool and shoing above error,
orig vmp-ed file runs fine

**Comment by Epoch1337** [comment]
You should unpack the Anti-Tamper first.

**Comment by greenozon** [comment]
Thanks for the reply!
Could you please hint how do you reach this step out?
is it just to dump the running process or one need to use some specific tool?..
